tsc error fixes
addressing the below issues:

node_modules/express-ajv-swagger-validation/src/middleware.d.ts:61:41 - error TS2749: 'AjvValidatorOptions' refers to a value, but is being used as a type here.                                                
                                                                                                                                                                                                                
61     new(options?: ajvValidatorOptions): AjvValidatorOptions;                                                                                                                                                 
                                           ~~~~~~~~~~~~~~~~~~~

node_modules/express-ajv-swagger-validation/src/middleware.d.ts:64:1 - error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.                                             

64 let InputValidationOptions: InputValidationOptionsStatic;
   ~~~

node_modules/express-ajv-swagger-validation/src/middleware.d.ts:70:44 - error TS2749: 'InputValidationOptions' refers to a value, but is being used as a type here.                                            

70     new(options?: inputValidationOptions): InputValidationOptions;
                                              ~~~~~~~~~~~~~~~~~~~~~~